version: '3'

services:
  db:
    image: mongo
    hostname: mongo
    container_name: mongo
    ports:
      - "27017:27017"
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    hostname: web
    container_name: web
    ports:
      - "5000:5000"
    depends_on:
      - db
  extractor:
    build:
      context: .
      dockerfile: Dockerfile-extractor
    hostname: extractor
    container_name: extractor
    ports:
      - "3000:3000"
    depends_on:
      - db
      - web
  expenses:
    build:
      context: .
      dockerfile: Dockerfile-expenses
    hostname: expenses
    container_name: expenses
    ports:
      - "666:666"
    depends_on:
      - db
      - web
